spring:
  application:
    name: store

payment-type: stripe

stripe:
  apiUrl: "www.stripe.com"
  enable: true
  timeout: 2000
  supported-currencies: USD, BDT, EURO

mail:
  host: https://smtp.gmail.com
  port: 5761